### ISSUE TITLE
Cannot trim undefined

### ISSUE THREAD

**Issue by Renari** [actions/create-release#65]
```Found 1 pull request(s) associated with commit 9755ecee1098eb5142a0bea53814e2413f50288d
  ##[error]Cannot read property 'trim' of undefined
  (node:18245) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trim' of undefined
      at e.exports (/actions-runner/_work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:572296)
      at Function.e.exports.sync (/actions-runner/_work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:570888)
      at /actions-runner/_work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:222656
      at Generator.next (<anonymous>)
      at s (/actions-runner/_work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:221551)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  (node:18245) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  (node:18245) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by Soitora** [comment]
Getting the same error here out of nowhere
